---
layout: default
title: Textile and Materials Glossary
author: Brontë Hebdon
permalink: /textilegloss/
---

<div class="glossary-button">
<h1>Textile & Materials Glossary</h1>

<div><br>
    <p class="about">This textile glossary brings together a broad range of vocabulary relating to French Directory and Consulate fashion plates, especially those in the <i>Journal des dames et des modes</i>. While by no means an exhaustive list, the purpose of this glossary is to provide quick reference material for those interested in reading the plate captions and descriptions, as well as those who want to know what the types of clothes idealized in the plates were actually made of. Please note that many textile terms changed over time according to location, language or evolving use ,and thus can have inconsistent meanings. Discrepancies can be cross-referenced from the list of sources below or from ARTFL's dictionary database.</p><br>
</div>


<h2 class="letter">A</h2>
<p><b class="textile">addatis</b>: Muslin or very fine, bright cotton cloth of medium to fine quality. The best samples came from Bengal, India in the seventeenth and eighteenth centuries. </p>
<p><b class="textile">agabance</b>: Also called agabaiiee, aggebance, and agibanis. Cotton fabric embroidered with silk, made in Aleppo, Syria. </p>
<p><b class="textile">agaric</b>: Cotton fabric similar to terry cloth, made with fine warp loop pile formed on wires. Commonly used for dresses. </p>
<p><b class="textile">aigrette</b>: Headdress with a white egret's feather decorated with diamonds. </p>
<p><b class="textile">ajamis</b>: Calico from the Near East. </p>
<p><b class="textile">alamodes</b>: A thin, light glossy black silk, not quilled.</p>
<p><b class="textile">à l'antique</b>: Suggestive of a specific costume common to another location, race or ethnic group. Examples are à la chemise, à la militaire, à la turque, à la peruque, à la niobe, à la mandoline, à la greque, à l'espagnole, à la polonaise, à la Billington, and à la Wurtenburg.</p>
<p><b class="textile">alapeen</b>: Mixed cloth of wool and silk primarily used for men's clothing but also sold to upholsterers. </p>
<p><b class="textile">alibanies</b>: Also called allibannees and allibanis. Striped cotton cloth carried to Holland from India, commonly produced as a mixed silk-and-cotton fabric in the seventeenth and eighteenth centuries.</p>
<p><b class="textile">allégeas</b>: Also called allegais or laychés. Fabric from India produced in two types. 1.) cotton, and 2.) herbs weaved with hemp or linen. Originally a striped cloth of mixed cotton-and-silk, this fabric was commonly red, blue and white, sometimes flowered and embellished with gold and silver thread. In the seventeenth century, allégeas was imported from South India.</p>
<p><b class="textile">alliballies</b>: Also called allibatis, alliabally, and allibali. Very fine muslin or a type of East Indian plain, brocaded or embroidered cotton. Some had selvages made with gold thread.  </p>
<p><b class="textile">aman/amand</b>:  A plain weave, blue cotton fabric made in the Near East. Formerly imported in France for the manufacture of curtains.</p>
<p><b class="textile">amadis</b>: Long, full sleeves gathered at intervals by bands around the arm.</p>
<p><b class="textile">amierties</b>: Also called ambertees, amertes, amertis, or emerties. A superior grade of white cotton cloth from India used in the lining of quilts. Amierties was a general use fabric, often used for block printing in England. </p>
<p><b class="textile">angleterre</b>: A lightweight, plain weave silk, often checked or striped. The term may have been intended to suggest silks patterned in the English taste. </p>
<p><b class="textile">angola</b>: Late eighteenth-century cashmere shawl imitation fabric. Name derived from Angora goat fur. </p>
<p><b class="textile">angola shirting</b>: Khaki shirting made of a mixture of wool and cotton in twill weave. </p>
<p><b class="textile">arains</b>: See armoisin or taffeta.</p>
<p><b class="textile">armoisin</b>: See sarcenet. A taffeta made in India, but of weaker and lower quality than the silk armoisins. The color is often carmine and red. There are two kinds. 1.) arains, which are striped taffetas and 2.) damasks, which are flowered taffetas. Often used for scholastic gowns, hatbands, and scarves.   </p>
<p><b class="textile">astarte</b>: A French silk dress fabric of fine quality, made in a twill weave and printed with bold designs in brilliant colors. </p>
<p><b class="textile">atchiabanes</b>: A plain white fabric of coarse quality for general domestic use. Atchiabanes was imported from Bengal in the eighteenth century. </p>
<p><b class="textile">atlas</b>: Silk satin made in India often done plain, striped, flowered in gold or solely in silk. As a warp-faced satin and weave fabric, it has silk warps and cotton wefts. Atlas varieties include cotonis, cancantas, calquiers, cotonis-bouilles, bouilles, charmay or quemkas. </p>
<p><b class="textile">augujli</b>: A coarse Syrian bagging made of cotton mixed with other fibers. Better grades are dyed blue or are white with another color.  </p>


<h2 class="letter">B</h2>
<p><b class="textile">bafta/baffetas</b>: Also called baffoted, baft, baftah, bufta, and baffs. A generic term for plain calico from India, varying from a coarse to fine quality. Those sent to Europe were usually white but those for Asian markets were more commonly dyed red, blue or black.  Used domestically in the seventeenth century, bafta was a cotton or cotton and silk fabric derived from Persian wool or yarn.</p>
<p><b class="textile">bajota</b>: A coarse, bleached cotton fabric formerly sold by the Holland East Indian Trading Co. </p>
<p><b class="textile">bajutapaux</b>: Also called bejutapaux and bayutapaux. A term used in the African trade to describe a coarse cotton cloth with blue and white or red and white stripes.</p>
<p><b class="textile">balais</b>: Silk ribbons. </p>
<p><b class="textile">balantine</b>: A woman's handbag, sometimes worn hanging from the belt; nicknamed reticule or ridicule and used during the Directory.</p>
<p><b class="textile">balzorine</b>: A light material of mixed cotton and worsted manufactured for women's dresses. </p>
<p><b class="textile">bas</b>: Stockings, most often made of silk (bas de soie) or wool (bas de laine).</p>
<p><b class="textile">basin</b>: A cotton cloth made in different qualities and fashions. All are white and without nap. Twilled and serge basin were used to make corsets, petticoats and curtains.  </p>
<p><b class="textile">batavia</b>: A silk fabric with a twill weave named after the place by the same name, now Jakarta, Indonesia, a Dutch colony in the eighteenth century. Batavia was fashionable in France in the 1760s. It was also known as Levantine and was often imitated in cotton. </p>
<p><b class="textile">batiste</b>: See chambray/cambric. A very fine, tightly woven fabric, usually linen or cotton.  </p>
<p><b class="textile">bavolet</b>: A cap worn by French peasant women.</p>
<p><b class="textile">bengal</b>: A cheap silk imported from India made of mixed cotton and silk. It was usually striped. </p>
<p><b class="textile">Betain</b>: Also called betaine or beteela. An obsolete term applied to Indian muslin used for neckties, saris, and head coverings. </p>
<p><b class="textile">betilles</b>: Muslin or white cotton cloth from Pondichéry. There are three varieties, one coarse, another very fine, and one bright. The fabric was sometimes dyed red, sometimes striped or flowered with embroidery, and was in demand in Europe for neckcloths. It was often used as the base cloth for fine embroidery.</p>
<p><b class="textile">bezane</b>: A French term for various bleached, striped, or dyed Bengal cottons and calicos in the eighteenth century.  </p>
<p><b class="textile">blonde</b>: Lightweight, shiny bobbin lace of raw silk.</p>
<p><b class="textile">boide</b>: Also called boi or boy. A coarse, heavy flannel in a plain, loose weave with cotton warp and wool. Boide was used in linings.</p>
<p><b class="textile">bolsas</b>: Also called bolzas or coutil. Bolsas was made of cotton thread imported from India in the seventeenth and eighteenth centuries. It was either all white or striped in yellow. </p>
<p><b class="textile">bombasin</b>: A silk cloth or a cloth woven from cotton thread. </p>
<p><b class="textile">bouille-cotonis/bouille-charmay</b>: See atlas. </p>
<p><b class="textile">bouracan</b>: Also called barracan, barragan, or camelot. A coarse cloth used to make coats. </p>
<p><b class="textile">bourdaloue</b>: A high crowned hat named after a famous seventeenth century Jesuit preacher. Under Louis XIV, the hat was turned up on each side. The final iteration turned up in three places – front, back and on the left side – where there was a button and a loop. Bourdaloue gave his name to the band around the hat. The band color initially imitated the hat color but soon became several bands of gold twisted around the crown. </p>
<p><b class="textile">boutida</b>: A fabric with a plain weave whose name has not yet been traced in any contemporary literature on textiles</p>
<p><b class="textile">bretagne</b>: A linen fabric of plain weave made in Brittany during the eighteenth century. It was often used for shirts because of its high quality. </p>
<p><b class="textile">bride</b>: The flange of a button or the border of a shirt.</p>
<p><b class="textile">brillanté</b>: A silk in a plain weave with a brocaded pattern.</p>
<p><b class="textile">brocade/brocart</b>: Traditionally, a type of silk damask with patterns woven in gold or silver. The main centers of production were Lyon and Tours.</p>
<p><b class="textile">brocatelle</b>: A gold or silk brocade with very rich ornamentation, usually polychrome and of Italian origin.</p>
<p><b class="textile">broché</b>: Brocade. A pattern made by wefts that only run the width of the motif and are then turned back.</p>
<p><b class="textile">buskin</b>: Calf-length, thick-soled laced boot originating in ancient Greece. Cothurnes were a type of Buskin that covered half of the leg and were laced in front.</p>

<h2 class="letter">C</h2>
<p><b class="textile">cadis</b>:  A worsted cloth. In England and America, cadis refers to cheap worsted tape or ribbon.</p>
<p><b class="textile">Cadogan</b>: a hairstyle, with a low queue behind, folded on itself and tied in the middle </p>
<p><b class="textile">cadrillé</b>: Checked; à carreaux in modern French. </p>
<p><b class="textile">calamande</b>: Also called calamandre or calamandre. A fabric with a fine gloss made in Flanders and Brabant. </p>
<p><b class="textile">calico</b>: Inexpensive, brightly printed cotton cloth woven with carded yarns in a plain weave. Originally a lightweight printed cotton cloth of Indian origin. Early calicos used elaborate animal designs while later calicos were of coarser fabric. The fabric was first woven, then painted, dyed or printed with wood blocks. </p>
<p><b class="textile">calotte</b>: A small bonnet or cap that covers only the top of the head.</p>
<p><b class="textile">calquiers</b>: See atlas or taffeta.</p>
<p><b class="textile">cambaye</b>: A strong, coarse East Indian cotton fabric resembling linen. </p>
<p><b class="textile">cambrai/ chambray</b>: See batiste or gingham. Derived from Cambrai in France, chambray encompassed a broad class of plain weave, yarn-dyed cotton fabrics with a colored warp and white weft. While often in plain color, it was also available in stripes, checks or other patterns.</p>
<p><b class="textile">cambraisines</b>: Fine cloth from Egypt.  </p>
<p><b class="textile">cambresine</b>: Fine linen fabric, a French term for fine, plain, lightweight cotton, linen fabric. </p>
<p><b class="textile">cambric</b>: A closely woven linen or cotton fabric. See batiste. </p>
<p><b class="textile">camlet/camblet</b>: Of Arabic origin, referring to pile or nap and to mohair. The name also applied to a wide variety of high quality, smooth fabrics made of wool, silk, etc., in plain or satin weave. Another type of camlet is a lightweight fabric woven of hard spun wool and cotton or linen yarn. </p>
<p><b class="textile">cancantas</b>: See atlas.</p>
<p><b class="textile">canezou</b>: A woman's high waisted jacket, usually sleeveless.</p>
<p><b class="textile">cannelé</b>: Any ribbed fabric with parallel ribs in the weft, formed by warp floats.</p>
<p><b class="textile">cannellé</b>: A warp-patterned silk with the textured effect in the ground or a pattern made entirely by the warp.  </p>
<p><b class="textile">cannetillé</b>: A weave with short ribs on the face of the fabric, giving the impression of small, monochrome checks.</p>
<p><b class="textile">cape</b>: Turned-down collar of a cloak that hangs loosely over the shoulders.</p>
<p><b class="textile">capelet</b>: A small cape or cape collar, attached to or separate from a coat or dress.</p>
<p><b class="textile">capote</b>: A stole, shawl, cloth or cape worn by women when going out in public that covers them from head to foot; a hood of taffeta; a type of women's hat often made of light fabric that is pleated and slipped; a type of women’s hat with a stiff brim and soft crown; a military greatcoat. </p>
<p><b class="textile">capperees</b>: Cheap blue and white checkered or striped cloth.  </p>
<p><b class="textile">caraco</b>: See casaquin. A type of small jacket fitted at the waist and flared in the back, with long, straight sleeves.  </p>
<p><b class="textile">carnagnole</b>: A men's jacket or short-skirted coat with wide, downturned collar, lapels, and rows of metal buttons; worn with trousers and red caps by the French Revolutionaries in 1792-93.</p>
<p><b class="textile">casaquin</b>:  See caraco. A woman’s short gown, worn over a petticoat with pleats in the back. </p>
<p><b class="textile">cashmere</b>: Very fine hair from Kashmir goats, used either pure or mixed with wool. Indian cashmere was imitated in France, where it was made with fine wool.</p>
<p><b class="textile">casimir</b>: See kerseymere. A durable, twill-woven, fine wool fabric.   </p>
<p><b class="textile">casquette à la liberté</b>: A soft red cap worn folded over; also called a bonnet rouge, or Phrygian cap.</p>
<p><b class="textile">charmay</b>: See altas.</p>
<p><b class="textile">chemise dress</b>: A woman’s day dress with a low neck gathered on a drawstring, usually worn with a sash.</p>
<p><b class="textile">chauters/chowters</b>: Plain white calico, usually of superior quality and used in shirting.  </p>
<p><b class="textile">chavonis</b>: Sheer, East Indian cotton muslin. </p>
<p><b class="textile">chenille</b>: Thread formed by a fine, twisted, and fringed ribbon, used as trimming, as part of a woven fabric, or as military ornament.  </p>
<p><b class="textile">chemise</b>: A thin undergarment made of cotton with tight, short sleeves and a low neckline.</p>
<p><b class="textile">chemisette</b>: A half-blouse worn to fill in a low neckline, fastened at the side. </p>
<p><b class="textile">cherusque</b>: A high fan-shaped collarette or ruff, similar to a Medici collar. Cherusques were made of cloth or lace.</p>
<p><b class="textile">chiffre</b>: Monogram</p>
<p><b class="textile">chikan/chilan</b>: Embroidered fine cotton muslin from India. </p>
<p><b class="textile">chiné</b>: Thread with various colors obtained by dying or printing; characterizing a fabric woven with chiné threads, either for the warp or the weft, or for both. It was pre-colored according to a certain motif, e.g. chiné velvet, chiné taffeta. </p>
<p><b class="textile">chintes</b>: Chintz in modern English, a painted or printed calico. Originally a glazed, plain weave cotton fabric, generally woven with a handspun fine warp and coarser, slack, twill filling, then decorated with brilliantly colored flower or striped patterns. First used in the eighteenth century for clothing, it was brilliantly colored and permanently dyed, while also lightweight and durable.</p>
<p><b class="textile">chites</b>: Also called chits, chittes, chite, and chitteie. A cotton fabric from India with a long-lasting dye that did not lose its luster. </p>
<p><b class="textile">circassienne</b>: A version of the robe à la polonaise in which the three tails or puffed swags are the same length and the sleeves are very short and funnel-shaped. It was worn at the time of the French Revolution.</p>
<p><b class="textile">cockade</b>: A rosette of ribbons, usually flat around a center button, attached to a hat or a lapel.</p>
<p><b class="textile">cocarde</b>: A knotted ribbon often adorning soldier's hats; later adapted to women's hats.</p>
<p><b class="textile">collet</b>: Collar.</p>
<p><b class="textile">contailles</b>: Low-grade French silk fabric. </p>
<p><b class="textile">cordonnet</b>: A tightly-twisted thick silk thread. It was often used as a brocading weft to give texture.</p>
<p><b class="textile">cornette</b>: cornett; a bonnet with a gathered crown that could be turned down.</p>
<p><b class="textile">cotonis/cotonis-bouilles</b>: See atlas.</p>
<p><b class="textile">cothurnes</b>: See buskin. </p>
<p><b class="textile">coutil</b>: See bolsas or twill. Also called coutis, coupis, or courtille. A type of fabric made from hemp that was very strong and close-knit. It was used for corsets. </p>
<p><b class="textile">couture</b>: Seam.</p>
<p><b class="textile">cravate</b>: cravat; a wide band of fabric worn as a necktie; ancestor of the tailored necktie</p>
<p><b class="textile">crepe/crape</b>: Fabric made with a twisted thread (fil de crêpe) or altered tension on alternate warp threads to achieve a puckered or crinkled effect. The best-known crepe is crêpe de Chine which was made of silk.</p>
<p><b class="textile">crépine</b>: A trim of very long, knotted fringes.</p>
<p><b class="textile">cretonne</b>: A heavy, white linen fabric used for upholstery. </p>
<p><b class="textile">culottes</b>: Knee breeches.</p>

<h2 class="letter">D</h2>
<p><b class="textile">damask</b>: a fine fabric of silk or linen, usually in a single color, elaborately patterned, and reversible. </p>
<p><b class="textile">dauphine</b>: a lightweight, plain weave wool upholstery fabric made in France in the eighteenth century; made of wool or a combination of wool and silk.</p>
<p><b class="textile">de laine</b>: a fine, woolen fabric first called mousseline de laine, or muslin of wool. </p>
<p><b class="textile">demi-bateau</b>: A silk top hat with a wide brim tilted in front and back. It was worn during the Directory period.</p>
<p><b class="textile">dentelle</b>: delicate lace made of linen, cotton, wool, silk or gold or silver thread. Formed with needles, books, bobbins, or machines in a variety of techniques.</p>
<p><b class="textile">doliman</b>: a cafetan; Turkish robe slit or open down the front, sometimes worn as a coat. </p>
<p><b class="textile">dorures</b>: A satin fabric ornamented in gold.  </p>
<p><b class="textile">douillette</b>: See redingote. A type of coat, loose-fitting, and without back pleat.</p>
<p><b class="textile">doussoutis; also called doussoutin</b>: mull; muslin, a plain-weave white cotton fabric of medium, fine and superfine quality, imported from India in the eighteenth century. </p>
<p><b class="textile">drap/drab</b>: wool broadcloth; a thick plain-weave wool used for outerwear. </p>
<p><b class="textile">droguet</b>: A silk textile with a small repeating pattern in no more than five colors, often used for men’s suiting. Droguets were often categorized further as lisérés, satinés, lustrinés, peruviennes, or prusiennes.  Also identified as a coarse wool fabric made with a cotton, silk or linen warp. </p>
<p><b class="textile">ducape</b>: A plain-weave stout silk fabric with a softer texture than the gros de Naples. </p>
<p><b class="textile">duck</b>: A plain-weave, heavy linen fabric with a glazed surface to shed water. </p>
<p><b class="textile">duvetyn</b>: A soft woolen fabric with spun silk or mercerized cotton back in a twill weave. It was used for coats, suits, dresses, and millinery trimmings.</p>

<h2 class="letter">E</h2>
<p><b class="textile">écorce d'arbre</b>: A baste fiber halfway between silk and linen. </p>
<p><b class="textile">effilé</b>: fringed.</p>
<p><b class="textile">embroidery</b>: ornamental designs made with a needle or hook and cotton, wool, linen, silk or metal thread on a cloth support.</p>
<p><b class="textile">en camayeu</b>: A cameo or monochrome effect created by two or more hues of the same color. </p>
<p><b class="textile">en dorures</b>: Decorative gold or other metal threads.</p>
<p><b class="textile">en fraise/fraise</b>: Decorative ruffs.</p>
<p><b class="textile">epaulette</b>: An ornamental shoulder piece, usually military in style.</p>
<p><b class="textile">eschantillon</b>: A showpiece of fabric used in sample books. </p>
<p><b class="textile">etamine</b>: A fine, lightweight worsted cloth, etamine was described in the late nineteenth century as transparent and meant to be worn over a contrasting color. </p>
<p><b class="textile">estrousoyé</b>: Silk fabric. </p>

<h2 class="letter">F</h2>
<p><b class="textile">façonné</b>: A fabric that has a woven pattern often created by brocading wefts.</p>
<p><b class="textile">faille</b>: A silk fabric with a ribbed effect.</p>
<p><b class="textile">favoris</b>: Sideburns/whiskers.</p>
<p><b class="textile">fichu</b>: A large, square kerchief worn by women to fill in the low neckline of a bodice. The fichu was often of linen fabric and was folded diagonally into a triangle then tied, pinned, or tucked into the front of the bodice; a scarf; it could also be worn on the head.</p>
<p><b class="textile">fichu en marmotte</b>: A headscarf knotted under the chin.</p>
<p><b class="textile">fichu religieuse</b>: A nun's handkerchief, made of embroidered muslin and worn around the neck. </p>
<p><b class="textile">filé</b>: See glace. A smooth metallic thread wound on a silk or linen core. </p>
<p><b class="textile">florence</b>: A silk with a satin weave.</p>
<p><b class="textile">florentine</b>: A lightweight silk taffeta originally made in Florence, then in Lyon.</p>
<p><b class="textile">floss</b>: Silk thread with no visible twist.</p>
<p><b class="textile">foulard</b>: A lightweight lustrous silk fabric from India. Taffeta foulards were silk neckcloths. </p>
<p><b class="textile">fourreau</b>: A woman's dress in which the back bodice and skirt were cut in one piece with no waist seam.</p>
<p><b class="textile">frisé</b>: A crimped or looped thread, frisé was known as frost in England.</p>
<p><b class="textile">froissé</b>: A creased item of clothing.</p>
<p><b class="textile">fustian</b>: A general term covering a large category of linen and cotton. Probably made partly of wool. </p>

<h2 class="letter">G</h2>
<p><b class="textile">gabrielle</b>: A frill or fluted ruff, sometimes worn as a standing collar.</p>
<p><b class="textile">galon</b>: Braid trimming.</p>
<p><b class="textile">ganse/gance</b>: Cord trim.</p>
<p><b class="textile">gartering</b>: A tape or braid tied around the calf to support stockings.</p>
<p><b class="textile">gauze</b>: Sheer, transparent cotton, silk or wool fabric in which the warp threads are twisted around the weft; used for trimmings and clothing items, the term can apply to any sheer or open fabric. </p>
<p><b class="textile">gaz(e)</b>: A light and transparent eighteenth-century cloth made of cotton and silk.  </p>
<p><b class="textile">gilet</b>: A vest or waistcoat.</p>
<p><b class="textile">gillsayé/giselle</b>: Sheer French fabric made of wool.  </p>
<p><b class="textile">gingham</b>: A cloth of pure cotton woven with dyed yarns in stripes and checks. </p>
<p><b class="textile">glace</b>: Plain metal-wrapped silk thread; used to make a fabric of the same name. </p>
<p><b class="textile">gland</b>: Small tassel trim.</p>
<p><b class="textile">glands à la mirza</b>: Small tassels in Persian style.</p>
<p><b class="textile">glissade</b>: A cotton lining for silk and cotton fabrics.  </p>
<p><b class="textile">gorgoran</b>: A type of gros de Tours fabric with a heavier warp and weft. During the Empire, the term was used to describe fabrics with vertical stripes produced by different kinds of weaves.</p>
<p><b class="textile">grand habit</b>: French court dress for ceremonial occasions. </p>
<p><b class="textile">grisette</b>: A small light fabric mixed of silk, cotton, etc. made in many colors and fashions.  </p>
<p><b class="textile">gros de Tours/gros de Naples/gros de Florence</b>: A plain-woven silk with warp and wefts doubled to increase durability. The fabric had a corded effect and was the staple silk fabric.  </p>
<p><b class="textile">guinée, guinea</b>: A white cotton fabric, the name was given in Marseille to cloth sent to Guinea; Cheap, brightly-colored Indian calicos, mostly striped or checkered; a slave trade French term used in the seventeenth and eighteenth century for cotton canvas in gray or dark blue. </p>
<p><b class="textile">guzenis</b>: An ordinary plain white calico similar to baftas and gurrahs. </p>

<h2 class="letter">H</h2>
<p><b class="textile">Habit</b>: tail-coat</p>
<p><b class="textile">hairbine</b>: A silk and worsted material with some amount of mohair, the fabric was used for men's clothing. </p>
<p><b class="textile">herringbone</b>: Any textile woven in a zigzag pattern resembling chevrons or the bones of a herring. </p>
<p><b class="textile">hessian</b>: Coarse, hempen cloth, the name is most likely indicative of its origin. </p>
<p><b class="textile">hollandoise</b>: At the end of the seventeenth century, this term was used for linen fabric printed with wax.</p>
<p><b class="textile">hongreline</b>: Riding coat worn by French coachmen and footmen.</p>

<h2 class="letter">I</h2>
<p><b class="textile">imperial</b>: A name given to several kinds of cloth e.g. imperial satin, imperial serge; another name for perpetuana, or lightweight twill of worsted and wool. </p>
<p><b class="textile">imperial shirting</b>: Bleached cotton shirting. </p>
<p><b class="textile">imperial tape</b>: Thick cotton tape. </p>
<p><b class="textile">indienne</b>: A painted or printed cotton fabric originally made in the Far East. It was first used to make informal clothing and later for upholstery.</p>
<p><b class="textile">indispensable</b>: A bag used in place of pockets.</p>
<p><b class="textile">inkle</b>: A tape or braid used for trimming dresses and bed curtains, for garters, stays and apron strings. </p>
<p><b class="textile">italienne</b>: A plain weave fabric with a second flushing warp. </p>

<h2 class="letter">J</h2>
<p><b class="textile">jabot</b>: shirt-front ruffle</p>
<p><b class="textile">jaconas/jaconet</b>: A thin, closely woven cotton textile, thicker than muslin, slighter than cambric, and thinner than mainsook; a fine, light cotton fabric, between muslin and percale, originally made in India.</p>
<p><b class="textile">jour zephr</b>: An obsolete French term for plain gauze. </p>
<p><b class="textile">juive</b>: Douillette that reached only to the calves.</p>
<p><b class="textile">jupon</b>: A petticoat skirt worn under the gown. </p>

<h2 class="letter">K</h2>
<p><b class="textile">keeses</b>: Also called kestes, quesos, or kesis. A thick cotton cloth with elaborate check in blue and white; a striped or solid colored fabric in brilliant colors from India; used for trousers.</p>
<p><b class="textile">kermichi/ kermiss</b>: A British term for cotton dress fabrics of inferior quality.  </p>
<p><b class="textile">Kerseymere</b>: See casimir. A fine, twill wool used in men’s vests, coats and breeches and women’s redingotes.</p>
<p><b class="textile">korathes</b>: Also called korottes, korolz, korattes, and korotes. A coarse cotton fabric from India used to make big neckties. </p>

<h2 class="letter">L</h2>
<p><b class="textile">lace tucker</b>: A piece of lace or linen worn around the top of a low-cut bodice to increase modesty.</p>
<p><b class="textile">lamé</b>: A fabric woven with strips of metal, often gold or silver. </p>
<p><b class="textile">lampas</b>: A patterned silk fabric in which the pattern is in a different weave structure from the ground; often used in upholstery.</p>
<p><b class="textile">lappets</b>: Decorative flaps, or hangings on headdresses or garments used in a religious setting.</p>
<p><b class="textile">lawn</b>: A linen fabric with a fine, transparent plain weave which can be finished to have a shiny, silk-like appearance.</p>
<p><b class="textile">leghorns</b>: A braided straw used to make hats.</p>
<p><b class="textile">leneau</b>: A gauze-weave in which warp yarns arranged in pairs cross and re-cross one another between picks of weft; a structure in which rows or areas of gauze weave are separated by, or combined with, areas of plain weave. </p>
<p><b class="textile">lévite</b>: A men's long frockcoat or women's long dress with deep cape collar; resembled a garment worn by Levite priests.</p>
<p><b class="textile">limace</b>: Also called limances, limaconne, limande or limanée. A striped cotton cloth of fine quality used domestic in the eighteenth century. </p>
<p><b class="textile">linen</b>: A cloth of many grades and weaves made from flax fibers; a very light and fine fabric Variations of linen include calicoes, cambricks, canvas, damasck, diaper, lawns, drilling and pack duck, etc. </p>
<p><b class="textile">liséré</b>: See droguet. The main weft thread, which, besides creating the pattern, also gives a texture to the fabric ground</p>
<p><b class="textile">lodier/loudrier</b>: A coarse blanket of wool.  </p>
<p><b class="textile">lohi</b>: A coarse, heavy handwoven dress fabric of wool from Kashmir.  </p>
<p><b class="textile">longhee</b>: Also called longyi, lungi, or loonghie. A plain weave Indian cotton fabric with a silk or gold border; a natural bleached or dyed cotton fabric used for loincloths.  </p>
<p><b class="textile">louisine</b>: A lightweight, silk fabric woven with twice as many warp ends than fillings to the square inch; a very thin, plain silk material suitable for children's wear and for slight summer costume.</p>
<p><b class="textile">luquoises</b>: A silk cloth from Lusques imitated in France with gold and silver thread.  </p>
<p><b class="textile">lustrine</b>: See droguet. A light, crisp plain silk in many colors with a high luster.  </p>

<h2 class="letter">M</h2>
<p><b class="textile">mallemoles</b>: Also called malmal, mollmol, and mulmull. A muslin or white cotton cloth from India; a plain white muslin; in the seventeenth and eighteenth centuries, a fine muslin often embroidered with floral motifs.  </p>
<p><b class="textile">mameluke sleeves</b>: Sleeves that extended to cover the hand. </p>
<p><b class="textile">mamondis</b>: Also called mahmud, mamoudi, and mamoudie. A hand woven Indian muslin and a general term for Indian calicos.  </p>
<p><b class="textile">mantelet</b>: A light shawl-like clothing accessory, typically made out of silk, worn around the shoulders when going out in public.</p>
<p><b class="textile">marbre</b>: A cloth made to resemble the veining of marble. </p>
<p><b class="textile">marceline</b>: A soft silk fabric; a type of light taffeta ordinarily used for dresses.</p>
<p><b class="textile">mauris</b>: See percale; also called mouris or moris; a white cotton cloth; an eighteenth century French term for percale imported from India.</p>
<p><b class="textile">melin</b>: Also called melis or meslins. A French hemp sailcloth. </p>
<p><b class="textile">merino</b>: Cloth woven from the wool of the Merino sheep. </p>
<p><b class="textile">mohere</b>: Also called mouaire or moire; cloth made from the wool of the angora goat imported from Turkey. Mohere was often mixed with silk.  </p>
<p><b class="textile">moire</b>: The term used to designate French ribbed silks. </p>
<p><b class="textile">moiré</b>: Fabric finished with a wavelike, watered effect caused by a special finishing technique.</p>
<p><b class="textile">montassies/mentasses</b>: A cloth with gold threading. </p>
<p><b class="textile">montichours</b>: A cloth of silk and cotton.  </p>
<p><b class="textile">moquette</b>: Also called mocade or moucade; raincoats made of linen, cotton or wool.  </p>
<p><b class="textile">mouchoirs</b>: Handkerchiefs usually of cotton cloth.  </p>
<p><b class="textile">mousseline</b>: See muslin. A light cotton fabric of a loose tabby weave, usually plain but occasionally decorated with embroidery. It was first made in India. </p>
<p><b class="textile">mull</b>: A plain weave, cotton fabric; muslin. </p>
<p><b class="textile">muslin</b>: A plain weave, cotton fabric; mull. </p>

<h2 class="letter">N</h2>
<p><b class="textile">nankeen</b>: A type of durable yellow cotton tabby cloth originally hand-loomed in China and used to make pants and vests. </p>
<p><b class="textile">Nilla</b>: A fabric made of a mixture of silk and baste fiber in East India. </p>
<p><b class="textile">Noyalls</b>: Strong, unbleached canvas made of hemp in various places in Brittany. </p>
<p><b class="textile">Nué</b>: See nuances.</p>

<h2 class="letter">O</h2>
<p><b class="textile">organdie</b>: Also called organdy or organdis; a kind of mousseline or a fine, sheer, very lightweight cotton fabric made of fine count, combed singles in open, plain weave, with a characteristic stiff, crisp, clear finish.  </p>
<p><b class="textile">orleans</b>: A dress material made of plain weave. The warp is of thin cotton while the weft is worsted. </p>
<p><b class="textile">orris</b>: Heavy ribbon or gimp trimming, sometimes woven with gold and silver. </p>

<h2 class="letter">P</h2>
<p><b class="textile">paduasoy</b>: Also called peau de soie. A heavy silk with a thick weft woven into a plain weave, sometimes with a pattern. Paduasoy was the heaviest of the dress silks.  </p>
<p><b class="textile">palatine</b>: Furs or other woven fabrics worn on the neck in the winter.</p>
<p><b class="textile">panne</b>: See plush. A silk fabric with pile, often a little longer than that of velvet and used principally in upholstery. In the eighteenth-century, silk panne from Lyon was highly desirable.</p>
<p><b class="textile">passements</b>: A silk fabric with narrow wares or trimmings including laces, galloons, gimps, fringes, and braids. </p>
<p><b class="textile">peau de poule</b>: A plain weave silk with a grainy, chicken skin-like surface.</p>
<p><b class="textile">peau de soie</b>: See paduasoy or taffeta. A taffeta weave of a particularly fine texture.  </p>
<p><b class="textile">pelache</b>: Also called peluche or pluche; a coarse, velvety, cotton, wool or silk fabric.  </p>
<p><b class="textile">pelisse</b>: A highly popular empire-waist coat or cape often lined with fur, extending to the knee or lower; a lightweight broadcloth used for women's clothes, especially capes fashionable in the second half of the eighteenth century.  </p>
<p><b class="textile">percale</b>: A plain, smooth, lightweight cotton fabric used for morning dresses. Printed percales were used for shirting. </p>
<p><b class="textile">perruque</b>: Wig.</p>
<p><b class="textile">perse</b>: Lightweight silk fabric associated with India.</p>
<p><b class="textile">Persian</b>: A thin, plain silk principally used for linings in coats, petticoats, and gowns in the eighteenth century. </p>
<p><b class="textile">peruvienne</b>: See droguet. A fabric of the droguet family, with a small textural pattern. </p>
<p><b class="textile">piqué</b>: A double-woven fabric, usually of cotton, with crosswise corded ribs or elaborate weaves.</p>
<p><b class="textile">platille</b>: A very white linen cloth.  </p>
<p><b class="textile">plissure</b>: A crease or pleat.</p>
<p><b class="textile">plush</b>: See panne. A warp pile fabric less closely woven than velvet with the pile cut longer, usually of wool. </p>
<p><b class="textile">poplin</b>:  A medium-weight, durable plain weave fabric with fine crosswise ribs; made of cotton, silk, or wool.</p>
<p><b class="textile">populées</b>: A cheap, checkered calico. </p>
<p><b class="textile">poulangis/poulangy</b>: Wool fabric.  </p>
<p><b class="textile">prussienne</b>: See droguet. A fabric of the droguet family originating in Berlin in the 1750s, prusienne had a taffeta ground with a warp thread of two colors. </p>

<h2 class="letter">Q</h2>
<p><b class="textile">quemkas</b>: See atlas. </p>

<h2 class="letter">R</h2>
<p><b class="textile">ramoneur</b>: A small, peaked hat similar to those worn by chimneysweeps; a blackish color. </p>
<p><b class="textile">ras</b>: A cloth made of mixed combing and carding wool. </p>
<p><b class="textile">ras de st. cyr</b>: French silk dress goods with cross ribs, usually in black.</p>
<p><b class="textile">rasta/raftas</b>: A French term for trousers. </p>
<p><b class="textile">ratteen/ratiné</b>: A nubbly ply yarn made by twisting thick and thin yarn under tension.</p>
<p><b class="textile">rayé</b>: Striped. </p>
<p><b class="textile">redingote</b>: See douillette. A long overcoat with overlapping front skirts and a wide collar.</p>
<p><b class="textile">rep</b>: See taffeta. A fabric with fine, closely-spaced horizontal ribs made of various fibers. Silk was most popular during the eighteenth century; used mainly for upholstery.</p>
<p><b class="textile">reticule/ridicule</b>: See balantine. </p>
<p><b class="textile">riband</b>: Ribbon.</p>
<p><b class="textile">robe foncée</b>: A gathered dress, especially one gathered at the sleeves.</p>
<p><b class="textile">rosconnes</b>: Linen cloth. </p>

<h2 class="letter">S</h2>
<p><b class="textile">santal</b>: See taffeta.  </p>
<p><b class="textile">sarcenet</b>: See armoisin. A fine, soft silk fabric used for dresses and ribbons. </p>
<p><b class="textile">satin</b>: A basic silk weave with long warp or weft floats to give a shiny, smooth surface appearance.</p>
<p><b class="textile">satiné</b>: See droguet.</p>
<p><b class="textile">sattinette</b>: A very thin type of satin used for summer nightgowns. </p>
<p><b class="textile">sautoir</b>: A small piece of cloth worn by women draped from the neck and tied around the chest</p>
<p><b class="textile">sayette</b>: Woolen or silk cloth. </p>
<p><b class="textile">saxone</b>: A mixed fabric of silk and linen.</p>
<p><b class="textile">schall</b>: A shawl worn around the shoulders.</p>
<p><b class="textile">seerhaudconnaes</b>: A cotton cloth of ordinary quality; a term for various Indian cotton muslin. </p>
<p><b class="textile">semple</b>: The system for selecting which warp threads to lift in order to weave the pattern on a drawloom.  </p>
<p><b class="textile">serge</b>: A cheap, strong calico made either plain or striped. Serge was used in making napkins, flags, linings, and sailcloth. </p>
<p><b class="textile">sergé</b>: A basic, durable twill weave of a diagonal pattern, or, by reversing direction, a herringbone or chevron pattern.</p>
<p><b class="textile">serpilliere</b>: A cheap, coarse cloth. </p>
<p><b class="textile">shag</b>: A fabric with a long nap on one side. Shag was usually made of silk and was occasionally worsted. </p>
<p><b class="textile">siamoise</b>: A large group of linen and cotton goods, some with additions of wool or silk. Siamoise was made in imitation of the magnificent garments worn by ambassadors of the King of Siam in 1684. It was a popular product of Lyon. </p>
<p><b class="textile">silesie</b>: A thin, twilled linen cloth, the term refers to many grades and patterns of linens, unbleached or dyed in colors and later imitated in cotton. The fabric was used for household purposes, lining clothing and window roller-blinds. </p>
<p><b class="textile">silk</b>: Cloth woven from the shiny, smooth filaments reeled from cocoons of the silkworm Bombyx mori. </p>
<p><b class="textile">silveret</b>: A half-silk mixed with cotton or wool used for men's clothing. </p>
<p><b class="textile">sorbec</b>: Metal-wrapped silk thread with a colored core. Yellow or white cores used gold and silver wrapped threads.</p>
<p><b class="textile">souci</b>: Also called sousee, sousaes, and soutis: A silk muslin striped in different colors, souci was sometimes called mousseline even though it was not made of cotton; a striped or checkered fabric of silk or a cotton-and-silk combination with big European demand; yellow-orange.</p>
<p><b class="textile">soosie/soosey</b>: A kind of silk, striped cloth also mixed with cotton. </p>
<p><b class="textile">soulier</b>: A shoe that covers the whole foot, typically made of leather.</p>
<p><b class="textile">soutache</b>: Braided trim.</p>
<p><b class="textile">spincer/spencer</b>: Dating from the 1790s, in men’s clothing the spencer was a waist-length double-breasted coat or jacket without tails; in women’s clothing the spencer is a fitted cardigan or jacket that reaches either waist-length or bust-length.</p>
<p><b class="textile">stinquerkes</b>: Cotton handkerchiefs.  </p>
<p><b class="textile">stuff</b>: A general term for worsted cloths. </p>

<h2 class="letter">T</h2>
<p><b class="textile">tabby</b>: A simple, basic weave also known as plain cloth or cloth weave. It was stronger and thicker than taffeta. </p>
<p><b class="textile">tabis</b>: Coarse taffeta.  </p>
<p><b class="textile">tabouret</b>: Shaded and striped worsteds found in several late-eighteenth-century Norwich merchants' sample books. </p>
<p><b class="textile">taffeta</b>: A fine, tightly woven silk fabric. Variations include crape, faille, florence, gros de Naples, gros de Tours, grosgain, marceline, muslin, peau de soie, and rep.</p>
<p><b class="textile">taffeta</b>:  Also called arains or armoisins. A lustrous silk cloth from India made plain, striped in gold, silver, checked, or flowered. The term derived from taftah, the Persian term which translates to 'very fine.' In the eighteenth century, the term covered a wide range of silk and silk/cotton goods, many striped or checked. </p>
<p><b class="textile">taffetas changeant</b>: A taffeta with warp and weft of different colors, creating an iridescent effect. </p>
<p><b class="textile">taffeta foulards</b>: Silk neckcloths. </p>
<p><b class="textile">taffetas peint</b>: Painted taffeta.</p>
<p><b class="textile">tarnetannes</b>: Also called tarlatanne or tarlatan. A muslin or white cotton cloth.  </p>
<p><b class="textile">tayelles/tayottes</b>: A belt made of cotton or wool.  </p>
<p><b class="textile">tiffany</b>: A thin, transparent silk or gauze.</p>
<p><b class="textile">tippet</b>: A long fur boa worn around the neck.</p>
<p><b class="textile">tollanette</b>: A fabric made of silk and cotton warp with woolen filling. The fabric could be plain, figured or printed and was similar to casimere. </p>
<p><b class="textile">toque</b>: A soft, draped, brimless, close-fitting cloth women’s hat; a muslin or white cotton cloth from India.  </p>
<p><b class="textile">toquet</b>: A peasant-style bonnet.</p>
<p><b class="textile">torade</b>: A cotton muslin from India.  </p>
<p><b class="textile">transparent</b>: A type of garment, often a dress, of finest brocade, lace or velvet. </p>
<p><b class="textile">treillis</b>: A French term for handmade lace.</p>
<p><b class="textile">tricote</b>:  A plain, warp-knit silk fabric with fine vertical lines on the face and cross ribs on the back.</p>
<p><b class="textile">trippe</b>: A kind of moquette or velvet stuff of woolen pile and goat's hair.</p>
<p><b class="textile">tulle</b>: Thin, transparent net made of fine cotton or silk thread. The fabric was first introduced to France at the end of the eighteenth century.  </p>
<p><b class="textile">twill</b>: See coutil. A plain, durable fabric of very tight weave, characterized by diagonal ribs or patterning.</p>

<h2 class="letter">U</h2>
<h2 class="letter">V</h2>
<p><b class="textile">vandykes</b>: A pointed pieces of trim used to decorate. They were named for Sir Anthony Van Dyck, the Flemish painter. </p>
<p><b class="textile">vane</b>: Padded French quilt made of piqué or calico. </p>
<p><b class="textile">velour</b>: Also called velvet, the weave is characterized by a pile raised in loops above the ground weave. The loops may be left alone or cut, creating "uncut" or "cut" velvet. </p>
<p><b class="textile">vestal veil</b>: full-length veil.</p>

<h2 class="letter">W</h2>
<p><b class="textile">warp</b>: The threads which are secured to the loom and run the length of the fabric. Some fabrics have more than one warp.</p>
<p><b class="textile">weft</b>: The threads that are woven into the warp by the weaver using a shuttle.</p>
<h2 class="letter">X</h2>
<h2 class="letter">Y</h2>
<h2 class="letter">Z</h2>
</div>
